# Generated by Django 2.0.2 on 2018-02-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='absent_member',
            field=models.ManyToManyField(blank=True, default=None, to='member.Member'),
        ),
    ]
